---
title: "My Publications"
output:
  html_document:
    toc: true
    toc_float: true
---

Here are all my publications.

----

<br>

# Peer-reviewed Papers
All my published or *in press* papers in scientific journals so far.

<br>

## 2020

Zizka A, Antunes Carvalho F, Calvente A, Rocio Baez-Lizarazo M, Cabral A, Coelho JFR, Colli-Silva M, Fantinati MR, Fernandes MF, **Ferreira-Araújo T**, Gondim Lambert Moreira F, Santos NMC, Santos TAB, dos Santos-Costa RC, Serrano FC, Alves da Silva AP, de Souza Soares A, Cavalcante de Souza PG, Calisto Tomaz E, Vale VF, Vieira TL, Antonelli A (2020). No one-size-fits-all solution to clean GBIF. *PeerJ* 8:e9916. [doi: 10.7717/peerj.9916](https://doi.org/10.7717/peerj.9916)

<br>

## 2019

Costa, S.Y.L.; Petean, F.F.; **Araújo, T.F.P.**; Medeiros, L.S.; Barros-Neto, L.F.; Paiva, R.E.C.; Bennemann, A.B.A.; Abrantes, Y.G.; Lira, M.G.S.; Lima, S.M.Q. (2019). Coleção ictiológica da Universidade Federal do Rio Grande do Norte: um relevante acervo de peixes da Caatinga e áreas adjacentes. *Boletim Sociedade Brasileira de Ictiologia* 129: 146-153. [link](http://www.sbi.bio.br/images/sbi/boletim-docs/2019/outubro_129.pdf)

<br>

## 2017

Lima, S.M.Q.; Berbel-Filho, W.M.; **Araújo, T.F.P.**; Lazzarotto, H.; Tatarenkov, A.; Avise, J.C. (2017). Headwater Capture Evidenced by Paleo-Rivers Reconstruction and Population Genetic Structure of the Armored Catfish (*Pareiorhaphis garbei*) in the Serra do Mar Mountains of Southeastern Brazil. *Frontiers in genetics* 8: 199. [doi: 10.3389/fgene.2017.00199](https://doi.org/10.3389/fgene.2017.00199)


<br>

# Theses


Master’s Thesis: From “ginga” to sardine: ethnoichthyology and molecular systematics of small fishes with cultural value of Brazilian coast (April 2020). Universidade Federal do Rio Grande do Norte. [pdf](files/master_thesis.pdf)


Bachelor’s Thesis: *Pareiorhaphis garbei* (Ihering 1911), a suckermouth amoured catfish of Atlantic Forest headwaters, southeast of Brazil: an endangered cryptic species complex? (November 2017). Universidade Federal do Rio Grande do Norte.